# Generated by Django 4.2 on 2024-02-08 15:36

import actions.archive_article
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archived_artical_attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.URLField()),
                ('file_name', models.FileField(blank=True, null=True, storage=actions.archive_article.OverWriteStorage(), upload_to=actions.archive_article.get_file_path)),
                ('location', models.TextField()),
                ('received_on', models.DateTimeField(auto_now_add=True)),
                ('processed_on', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('waiting', 'waiting'), ('processed', 'processed'), ('failed', 'failed')], max_length=12)),
                ('notes', models.TextField(default='N/A')),
            ],
        ),
    ]
