# Generated by Django 4.2 on 2024-02-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archived_artical_attribute',
            name='location',
            field=models.TextField(default='N/A'),
        ),
    ]
