# Generated by Django 4.2 on 2024-02-13 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_alter_archived_artical_attribute_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archived_artical_attribute',
            name='location',
        ),
    ]
