# Generated by Django 4.2 on 2024-02-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_remove_archived_artical_attribute_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=100)),
                ('provider_address', models.URLField()),
                ('host_name', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=50)),
                ('pass_code', models.CharField(max_length=50)),
                ('last_accessed_at', models.DateTimeField()),
                ('last_status', models.CharField(choices=[('waiting', 'waiting'), ('processed', 'processed'), ('failed', 'failed')], max_length=15)),
                ('next_due_date', models.DateField()),
                ('frequency', models.IntegerField(default=1)),
            ],
        ),
    ]
