# Generated by Django 4.2 on 2024-02-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0005_remove_provider_model_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider_model',
            name='password',
            field=models.CharField(default='aaa', help_text='Use \'[algo]$[salt]$[hexdigest]\' or use the <a href="password/">change password form</a>.', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
