# Generated by Django 4.2 on 2024-02-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0008_alter_provider_model_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider_model',
            name='data',
            field=models.JSONField(default='q'),
            preserve_default=False,
        ),
    ]
