# Generated by Django 4.2 on 2024-02-16 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0010_provider_meta_data_api_remove_provider_model_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider_meta_data_api',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='api_provider', to='actions.provider_model'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='provider_meta_data_ftp',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fpt_provider', to='actions.provider_model'),
        ),
    ]
