# Generated by Django 4.2 on 2024-02-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0011_provider_meta_data_api_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider_meta_data_api',
            name='last_pull_status',
            field=models.CharField(default='pass', max_length=10),
        ),
        migrations.AddField(
            model_name='provider_meta_data_api',
            name='next_due_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='provider_meta_data_ftp',
            name='last_pull_status',
            field=models.CharField(default='pass', max_length=10),
        ),
        migrations.AddField(
            model_name='provider_meta_data_ftp',
            name='next_due_date',
            field=models.DateTimeField(null=True),
        ),
    ]
